services:
  postgres:
    image: postgres
    container_name: zynapse_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restapi_dev
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../pg_data:/var/lib/postgresql/data/
    # env_file:
    #  - .env
    ports:
      - '5432:5432'

volumes:
    postgres:
